---
- name: Deploy firewall
  hosts: all
  become: true
  gather_facts: false
  roles:
    - common

- name: Deploy lamp stack database
  hosts: lamp-db
  become: true
  gather_facts: false
  roles:
    - mysql

- name: Deploy lamp stack application
  hosts: lampweb
  become: yes
  gather_facts: false
  roles:
    - httpd-php

