---
# tasks file for roles/roles/mysql
- name: Install packages
  yum:
    name:
      - mariadb-server
      - MySQL-python
    state: installed

- name: Copy MySql config
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf

- name: Start / enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - mariadb
    - firewalld

- name: Configure firewall rules
  firewalld:
    port: "{{ mysql_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled

- name: Create application database
  mysql_db:
    name: "{{ dbname }}"
    state: present

- name: Create application db user
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ dbpassword }}"
    host: "{{ ansible_host }}"
    priv: "*.*:ALL"
    state: present

- name: Copy db load scripts
  template:
    src: templates/db-load-script.sql.j2
    dest: /tmp/db-load-script.sql

- name: Load inventory data
  shell: mysql -f < /tmp/db-load-script.sql