apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - microservice.yaml

# transformers

commonAnnotations:
  author: gnomesoft
  source: github.com/gnomesoft/gnomesoft-mono
  app: apps/go-hello
  infra: infra/kustomize/go-hello

generatorOptions:
  immutable: true


