apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-hello
  name: go-hello-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-hello
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      containers:
      - image: gnomesoft/go-hello
        name: go-hello-microservice
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15
          failureThreshold: 3