---
- name: Deploy lamp stack application
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - include_tasks: tasks/common.yml

- name: Deploy lamp stack database
  hosts: lamp-db
  become: true
  gather_facts: false
  tasks:
    - include_tasks: tasks/db.yml

- name: Deploy lamp stack application
  hosts: lampweb
  become: yes
  gather_facts: false
  tasks:
    - include_tasks: tasks/web.yml

