---
# tasks file for roles/httpd-php
- name: Install httpd and php
  yum:
    name:
      - httpd
      - php
      - php-mysql
    state: present

- name: Install web role dependencies
  yum:
    name: git
    state: installed

- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: insert firewalld rule for httpd
  firewalld:
    port: "{{ httpd_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled

- name: Set index.php as the default packages
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'DirectoryIndex index.html'
    replace: 'DirectoryIndex index.php'

- name: "Start httpd service"
  service:
    name: httpd
    state: started
    enabled: true

- name: Copy the application code from repo
  git:
    repo: "{{ repository }}"
    dest: /var/www/html/
    force: yes

- name: Create index.php
  template:
    src: templates/index.php.j2
    dest: /var/www/html/index.php